bolao:
  selecoes:
    - África Do Sul
    - Alemanha
    - Argélia
    - Argentina
    - Austrália
    - Brasil
    - Camarões
    - Chile
    - Coreia Do Sul
    - Coreia Do Norte
    - Costa Do Marfim
    - Dinamarca
    - Eslováquia
    - Eslovênia
    - Espanha
    - Estados Unidos
    - França
    - Gana
    - Grécia
    - Holanda
    - Honduras
    - Inglaterra
    - Itália
    - Japão
    - México
    - Nigéria
    - Nova Zelândia
    - Paraguai
    - Portugal
    - Sérvia
    - Suíça
    - Uruguai
